name: lhstore
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0
  google_sign_in: ^6.1.6
  flutter_easyloading: ^3.0.5
  firebase_storage: ^11.5.2
  image_network: ^2.5.4+1
  image_picker: ^0.8.7+1
  flutter_inappwebview: ^5.8.0
  dio: ^5.4.0
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/image/

